onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /memory_tb/imem/i_Cache/clk
add wave -noupdate /memory_tb/imem/i_Cache/rst
add wave -noupdate /memory_tb/imem/i_Cache/wen
add wave -noupdate /memory_tb/imem/i_Cache/en
add wave -noupdate /memory_tb/imem/i_Cache/addr
add wave -noupdate /memory_tb/imem/i_Cache/write_data_array
add wave -noupdate /memory_tb/imem/i_Cache/write_tag_array
add wave -noupdate /memory_tb/imem/i_Cache/data_out
add wave -noupdate /memory_tb/imem/i_Cache/miss_detected
add wave -noupdate /memory_tb/imem/i_Cache/tag
add wave -noupdate /memory_tb/imem/i_Cache/set
add wave -noupdate /memory_tb/imem/i_Cache/set_enable
add wave -noupdate /memory_tb/imem/i_Cache/t1
add wave -noupdate /memory_tb/imem/i_Cache/t2
add wave -noupdate /memory_tb/imem/i_Cache/t3
add wave -noupdate /memory_tb/imem/i_Cache/t4
add wave -noupdate /memory_tb/imem/i_Cache/t5
add wave -noupdate /memory_tb/imem/i_Cache/word
add wave -noupdate /memory_tb/imem/i_Cache/next_word
add wave -noupdate /memory_tb/imem/i_Cache/w1
add wave -noupdate /memory_tb/imem/i_Cache/w2
add wave -noupdate /memory_tb/imem/i_Cache/data_way_select
add wave -noupdate /memory_tb/imem/i_Cache/data_in_way0
add wave -noupdate /memory_tb/imem/i_Cache/data_in_way1
add wave -noupdate /memory_tb/imem/iFSM/write_d_data_array
add wave -noupdate /memory_tb/imem/i_Cache/data_out_way0
add wave -noupdate /memory_tb/imem/i_Cache/data_out_way1
add wave -noupdate /memory_tb/imem/i_Cache/data_in
add wave -noupdate /memory_tb/imem/iFSM/write_i_data_array
add wave -noupdate /memory_tb/imem/iFSM/memory_address
add wave -noupdate /memory_tb/imem/i_Cache/word_enable
add wave -noupdate /memory_tb/imem/i_Cache/word_sel
add wave -noupdate /memory_tb/imem/iFSM/state
add wave -noupdate /memory_tb/imem/i_Cache/metadata_in_way0
add wave -noupdate /memory_tb/imem/i_Cache/metadata_in_way1
add wave -noupdate /memory_tb/imem/i_Cache/metadata_out_way0
add wave -noupdate /memory_tb/imem/i_Cache/metadata_out_way1
add wave -noupdate /memory_tb/imem/i_Cache/meta0_wen
add wave -noupdate /memory_tb/imem/i_Cache/meta1_wen
add wave -noupdate /memory_tb/imem/i_Cache/data0_wen
add wave -noupdate /memory_tb/imem/i_Cache/data1_wen
add wave -noupdate /memory_tb/imem/i_Cache/lru
add wave -noupdate /memory_tb/imem/i_Cache/valid0
add wave -noupdate /memory_tb/imem/i_Cache/valid1
add wave -noupdate /memory_tb/imem/i_Cache/tag_match_way0
add wave -noupdate /memory_tb/imem/i_Cache/tag_match_way1
add wave -noupdate /memory_tb/imem/iFSM/IDLE
add wave -noupdate /memory_tb/imem/iFSM/WAIT
add wave -noupdate /memory_tb/imem/iFSM/clk
add wave -noupdate /memory_tb/imem/iFSM/rst
add wave -noupdate /memory_tb/imem/iFSM/d_miss_detected
add wave -noupdate /memory_tb/imem/iFSM/i_miss_detected
add wave -noupdate /memory_tb/imem/iFSM/d_miss_address
add wave -noupdate /memory_tb/imem/iFSM/i_miss_address
add wave -noupdate /memory_tb/imem/iFSM/memory_data_valid
add wave -noupdate /memory_tb/imem/iFSM/d_stall
add wave -noupdate /memory_tb/imem/iFSM/i_stall
add wave -noupdate /memory_tb/imem/iFSM/write_d_tag_array
add wave -noupdate /memory_tb/imem/iFSM/write_i_tag_array
add wave -noupdate /memory_tb/imem/iFSM/set_which_cache_data
add wave -noupdate /memory_tb/imem/iFSM/rst_which_cache_data
add wave -noupdate /memory_tb/imem/iFSM/which_cache_data
add wave -noupdate /memory_tb/imem/iFSM/set_which_cache_addr
add wave -noupdate /memory_tb/imem/iFSM/rst_which_cache_addr
add wave -noupdate /memory_tb/imem/iFSM/which_cache_addr
add wave -noupdate /memory_tb/imem/iFSM/init
add wave -noupdate /memory_tb/imem/iFSM/shift_reg
add wave -noupdate /memory_tb/imem/iFSM/nxt_state
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {255 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 282
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {140 ns} {354 ns}
